### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by niky1989** [PowerFeather/powerfeather-demo#1]
I had this error compiling the Demo

c:\Users\abcd\Documents\Arduino\libraries\ESPAsyncWebServer\src\WebAuthentication.cpp: In function 'bool getMD5(uint8_t*, uint16_t, char*)':
c:\Users\abcd\Documents\Arduino\libraries\ESPAsyncWebServer\src\WebAuthentication.cpp:74:3: error: 'mbedtls_md5_starts_ret' was not declared in this scope; did you mean 'mbedtls_md5_starts'?
   74 |   mbedtls_md5_starts_ret(&_ctx);
      |   ^~~~~~~~~~~~~~~~~~~~~~
      |   mbedtls_md5_starts
c:\Users\abcd\Documents\Arduino\libraries\ESPAsyncWebServer\src\WebAuthentication.cpp:75:3: error: 'mbedtls_md5_update_ret' was not declared in this scope; did you mean 'mbedtls_md5_update'?
   75 |   mbedtls_md5_update_ret(&_ctx, data, len);
      |   ^~~~~~~~~~~~~~~~~~~~~~
      |   mbedtls_md5_update
c:\Users\abcd\Documents\Arduino\libraries\ESPAsyncWebServer\src\WebAuthentication.cpp:76:3: error: 'mbedtls_md5_finish_ret' was not declared in this scope; did you mean 'mbedtls_md5_finish'?
   76 |   mbedtls_md5_finish_ret(&_ctx, _buf);
      |   ^~~~~~~~~~~~~~~~~~~~~~
      |   mbedtls_md5_finish
c:\Users\abcd\Documents\Arduino\libraries\ESPAsyncWebServer\src\AsyncEventSource.cpp: In member function 'void AsyncEventSourceClient::_queueMessage(AsyncEventSourceMessage*)':
c:\Users\abcd\Documents\Arduino\libraries\ESPAsyncWebServer\src\AsyncEventSource.cpp:189:7: error: 'ets_printf' was not declared in this scope; did you mean 'vswprintf'?
  189 |       ets_printf("ERROR: Too many messages queued\n");
      |       ^~~~~~~~~~
      |       vswprintf

**Comment by powerfeatherdev** [comment]
Hi, are you per chance using Arduino 3.0.0+?  Last time I checked, ESPAsyncWebServer (third party library) has issues building on the newest version.

**Comment by niky1989** [comment]
I use Arduino IDE 2.3.2

**Comment by powerfeatherdev** [comment]
Sorry, I meant arduino-esp32 3.0.0+. I believe you have the same issue as: https://github.com/me-no-dev/ESPAsyncWebServer/issues/1410. You would need to downgrade to arduino-esp32 2.x, or apply the patch in that thread.

**Comment by niky1989** [comment]
Solved using arduino-esp32 2.0.13 thanks

**Comment by powerfeatherdev** [comment]
Glad its ok now, closing this issue!
